a=int(input("a"))
b=int(input("b"))
d=int(input("d"))
c=a+b
print("Addition:\t\t",c)
a=int(input("a"))
b=int(input("b"))
c=a-b
print("enper:\t\t",c)
a=int(input("a"))
b=int(input("b"))
c=a*b
print("enter:\t\t",c)
a=int(input("a"))
b=int(input("b"))
c=a/b
print("enter:\t\t",c)
a=int(input("a"))
b=int(input("b"))
c=a%b
print("enter:\t\t",c)
a=int(input("a"))
b=int(input("b"))
c=a//b
print("enter:\t\t",c)